import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { BackgroundMusic } from "@/components/BackgroundMusic";
import { FetchRetryProvider } from "@/components/FetchRetryProvider";
import { WinnerAnnouncementModal } from "@/components/WinnerAnnouncementModal";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <FetchRetryProvider>
          <BackgroundMusic />
          {children}
          <WinnerAnnouncementModal />
        </FetchRetryProvider>
      </body>
    </html>
  );
}
